# A key practice is to install EVERYTHING possible using brew, brew cask, or mas.
# This is my attempt to do so!

cask_args appdir: "/Applications", require_sha: true

# * initial setup
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "homebrew/services"
tap "buo/cask-upgrade"

# * brews
brew "mas"
brew "git"
brew "wget"
brew "htop"
brew "direnv"
brew "ripgrep"
brew "watch"
brew "geoip"
brew "ispell"
brew "aspell"
brew "tree"
brew "jq"  # lightweight json processor
brew "graphviz"
brew "pandoc"
brew "plantuml"
brew "ledger"
brew "pngpaste"
brew "youtube-dl"
brew "mplayer", args: ["with-mac-metal"]
brew "gawk"
brew "findutils"
brew "cloc"
brew "the_silver_searcher"
brew "ripgrep"
brew "imagemagick"
brew "gifsicle"

# gpg setup
brew "gnupg"
cask "gpg-suite-pinentry"

# * zsh
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

# * mas
mas "Bitwarden", id: 1352778147
mas "WhatsApp Desktop", id: 1147396723
mas "keynote", id: 409183694
mas "numbers", id: 409203825
mas "pages", id: 409201541

# * casks
cask "telegram-desktop"
cask "phantomjs"
cask "hey"
cask "iterm2"
cask "postman"
cask "spotify"
cask "slack"
cask "datagrip"
cask "mactex-no-gui"
cask "kindle"
cask "wireshark"
cask "zulip"
cask "dash"

# * emacs
tap "railwaycat/emacsmacport"
brew "railwaycat/emacsmacport/emacs-mac", args: ["with-mac-metal", "with-starter"]

# * clojure & java
tap "clojure/tools"
tap "mdogan/zulu"
tap "AdoptOpenJDK/openjdk"
tap "borkdude/brew"

brew "mvn"
brew "leiningen"
brew "clojure/tools/clojure@1.10.3.929"
brew "jenv"
brew "clojure-lsp", args: ["HEAD"]
brew "borkdude/brew/babashka"

cask "zulu-jdk11"
cask "adoptopenjdk11"

# * haskell
brew "stack"
brew "haskell-language-server"
brew "ghc"

# * virtualization
cask "utm"

# * ruby
brew "rbenv"
brew "ruby-build"

# * node
brew "node@14"

# * vpn
cask "tunnelblick"

# * blog
brew "hugo"

# * github
brew "act"
