# A key practice is to install EVERYTHING possible using brew, brew cask, or mas.
# This is my attempt to do so!

cask_args appdir: "/Applications"

# * initial setup
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "buo/cask-upgrade"
tap "homebrew/cask-fonts"

# * brews

brew "mas"
brew "git"
brew "htop"
brew "gnupg"
brew "direnv"
brew "ripgrep"
brew "watch"
brew "geoip"
brew "ispell"
brew "tree"
brew "jq"  # lightweight json processor
brew "graphviz"
brew "pandoc"
brew "gnupg"
brew "github-keygen"
brew "pinentry-mac"

# * mas
mas "Bitwarden", id: 1352778147
mas "WhatsApp Desktop", id: 1147396723


# * casks
cask "telegram-desktop"
cask "phantomjs"
cask "hey"
cask "spectacle"
cask "iterm2"
cask "postman"
cask "slack"
cask "datagrip"
cask "mactex-no-gui"
cask "kindle"
cask "steam"


# * emacs
tap "railwaycat/emacsmacport"
brew "railwaycat/emacsmacport/emacs-mac", args: ["with-mac-metal", "with-starter"]


# * clojure & java
brew "leiningen"
tap "clojure/tools"
brew "clojure/tools/clojure"
tap "mdogan/zulu"
cask "zulu-jdk11"
tap "AdoptOpenJDK/openjdk"
cask "adoptopenjdk11"
