# User configuration
export MANPATH="/usr/local/man:$MANPATH"
export PATH="/Users/wferreir/dotfiles/scripts:/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export LEIN_USE_BOOTCLASSPATH=no
export GPG_TTY=$(tty)
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

alias ls="ls -GFh"
alias iroh="cd ~/code/iroh"
alias sync-brew="brew bundle --verbose --cleanup --file ~/code/dotfiles/macos/Brewfile && brew cu -f -a"
alias sync-syms="~/code/dotfiles/macos/symlinks.sh"
alias sync-zsh="source ~/.zshrc"
alias java-create-project="mvn archetype:generate"

export PATH="/Users/wferreir/.gem/ruby/2.6.0/bin:$PATH"
export PATH="$HOME/.jenv/bin:$PATH"

# make doom emacs available anywhere
export PATH="$HOME/.emacs.d/bin:$PATH"

export LDFLAGS="-L/opt/homebrew/opt/node@14/lib"
export CPPFLAGS="-I/opt/homebrew/opt/node@14/include"

LANG=en_US.UTF-8;
export LANG
export LC_ALL=$LANG

# eval
eval "$(jenv init -)"
eval "$(direnv hook zsh)"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# zsh plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export PATH="/opt/homebrew/opt/node@14/bin:$PATH"
if [ -e /Users/wferreir/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/wferreir/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

# android
export ANDROID_HOME=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/tools/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
