# User configuration

export MANPATH="/usr/local/man:$MANPATH"
export PATH="/Users/wferreir/dotfiles/scripts:/opt/homebrew/bin:$PATH"
export LEIN_USE_BOOTCLASSPATH=no
export GPG_TTY=$(tty)
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/opt/homebrew/share/zsh-syntax-highlighting/highlighters

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -GFh'

alias zshconfig="mate ~/.zshrc"
alias esource="cd $HOME/repos/reifyhealth/esource-service/"
alias study-sheet="cd $HOME/repos/reifyhealth/study-sheet/"
alias idrsa="ssh-add $HOME/.secrets/keys/id_rsa"
alias sync-brew="brew bundle --verbose --cleanup --file ~/dotfiles/macos/Brewfile"

eval "$(direnv hook zsh)"

# zsh plugins
source /opt/homebrew/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
