((org-mode . ((eval . (progn (turn-off-auto-fill)
                             (text-scale-set 1)
                             (turn-on-olivetti-mode)))
              (fill-column . 80)
              (visual-fill-column-width . 80)
              (olivetti-body-width . 80)
              (mode . visual-line)
              (mode . visual-fill-column))))
